replicaCount: 1

image:
  repository: 863518427890.dkr.ecr.us-east-1.amazonaws.com/cmm-zpl/zpl-flask-be
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: angular.203.0.113.10.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
